import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import './globals.css';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <Script id='clara-chatwoot-sdk' strategy='lazyOnload'>
          {`
          (function(d,t) {
        var BASE_URL="https://clara-support-staging.creditdirect.ng";
        var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=BASE_URL+"/packs/js/sdk.js";
        g.defer = true;
        g.async = true;
        s.parentNode.insertBefore(g,s);
        g.onload=function(){
          window.chatwootSDK.run({
            websiteToken: 'bRJQh5E1gAzCLyWMkACAa1L3',
            baseUrl: BASE_URL
          })
        }
      })(document,"script");
        `}
        </Script>

        {children}
      </body>
    </html>
  );
}
